### ISSUE TITLE
LO Version >7.3 does not accept the AddonBuilder

### ISSUE THREAD

**Issue by kkle2023** [EliseyP/BasicAddonBuilder_LibreOffice7#1]
It is not possible to install the newest version of the addonbilder. After the process occurs an error. After the restart the extension is grey and the status of the oxt is unknown.
![Bildschirmfoto_2023-04-15_12-38-06](https://user-images.githubusercontent.com/59770558/232209047-1fe62a99-11e7-4966-969e-cbdfd6a524dd.png)

**Comment by EliseyP** [comment]
Please - what version of LibreOffice and your OS?
(I have LO 7.5.2 on Debian 12).

**Comment by kkle2023** [comment]
Excuse me: it was my mistake. after i installed the LO-python package everything is running fine. thanks for your effort
